data_source jaffle_dbt:
  type: postgres
  connection:
    host: localhost
    port: 5432
    username: dbt
    password: secret
    database: dbt
    schema: postgres

soda_cloud:
  host: dev.sodadata.io
  api_key_id: {API_KEY_ID}
  api_key_secret: {API_KEY_SECRET}
